name: Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:

  test:

    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: yarn install --immutable --immutable-cache --check-cache
        # --immutable: Abort with an error exit code if the lockfile was to be modified
        # --immutable-cache: Abort with an error exit code if the cache folder was to be modified
        # --check-cache: Always refetch the packages and ensure that their checksums are consistent

      - name: Run tests
        run: yarn test
